In [1]:
!pip install requests pandas

Requirement already satisfied: requests in c:\users\tedi\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: pandas in c:\users\tedi\anaconda3\lib\site-packages (1.3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\tedi\anaconda3\lib\site-packages (from requests) (1.26.6)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\tedi\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tedi\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tedi\anaconda3\lib\site-packages (from requests) (2021.5.30)
Requirement already satisfied: numpy>=1.17.3 in c:\users\tedi\anaconda3\lib\site-packages (from pandas) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\tedi\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\tedi\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\tedi\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [3]:
import requests
import pandas as pd

In [5]:
import subprocess

# Define the URL and output file name
url = "https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=1706&Year=1998&Month=1&Day=14&timeframe=3&submit= Download+Data"
output_file = "climate_data_1998_1.csv"

# Use subprocess to execute the wget command
subprocess.run(["wget", "--content-disposition", "-O", output_file, url])

CompletedProcess(args=['wget', '--content-disposition', '-O', 'climate_data_1998_1.csv', 'https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=1706&Year=1998&Month=1&Day=14&timeframe=3&submit= Download+Data'], returncode=0)

In [6]:
import os
os.getcwd()

'C:\\Users\\Tedi'

In [7]:
import subprocess

# Define the URL for yearly data (timeframe set to 4 for yearly)
def download_yearly_data(year):
    url = f"https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=1706&Year={year}&Month=1&Day=1&timeframe=4&submit= Download+Data"
    output_file = f"climate_data_{year}_yearly.csv"
    
    # Use subprocess to execute the wget command
    subprocess.run(["wget", "--content-disposition", "-O", output_file, url])

# Download yearly data for each year from 2004 to 2023
for year in range(2004, 2024):
    download_yearly_data(year)

In [9]:
import os
download_folder = "E:\GIS\projects\climate_data"
os.chdir(download_folder)

In [11]:
import subprocess

# Define the URL for yearly data (timeframe set to 4 for yearly)
def download_yearly_data(year):
    url = f"https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=1706&Year={year}&Month=1&Day=1&timeframe=4&submit= Download+Data"
    output_file = f"climate_data_{year}_yearly.csv"
    
    # Use subprocess to execute the wget command
    subprocess.run(["wget", "--content-disposition", "-O", output_file, url])

# Download yearly data for each year from 2004 to 2023
for year in range(2004, 2024):
    download_yearly_data(year)

In [12]:
import subprocess

# Define the URL for yearly data (timeframe set to 4 for yearly)
def download_yearly_data(station_id, year):
    url = f"https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID={station_id}&Year={year}&Month=1&Day=1&timeframe=4&submit= Download+Data"
    output_file = f"climate_data_{station_id}_{year}_yearly.csv"
    
    # Use subprocess to execute the wget command
    subprocess.run(["wget", "--content-disposition", "-O", output_file, url])

# List of station IDs for Ontario (assuming you have the list of all 1643 station IDs)
station_ids = [3913]  # replace with actual station IDs

# Specific years to download data for
years_to_download = [2004, 2016, 2023]

# Download yearly data for each specific year (2004, 2016, and 2023) for each station
for station_id in station_ids:
    for year in years_to_download:
        download_yearly_data(station_id, year)

In [16]:
import pandas as pd

# Load the CSV file into a pandas DataFrame
file_name = "Station_list.csv"  # Replace with your file name
data = pd.read_csv(file_name)

# Clean up the 'Province' column
data['Province'] = data['Province'].str.strip().str.title()

# Check unique values in 'Province' for debugging
print("Unique values in 'Province':", data['Province'].unique())

# Filter the data for Province = "Ontario"
filtered_data = data[data['Province'] == 'Ontario']

# Save the filtered data to a new CSV file
if not filtered_data.empty:
    filtered_data.to_csv("Ontario_Stations.csv", index=False)
    print("Filtered data saved to 'Ontario_Stations.csv'.")
else:
    print("No data matches the filter criteria.")

# Display the filtered data
print(filtered_data)

Unique values in 'Province': ['British Columbia' 'Yukon Territory' 'Northwest Territories' 'Nunavut'
 'Alberta' 'Saskatchewan' 'Manitoba' 'Ontario' 'Quebec' 'New Brunswick'
 'Nova Scotia' 'Prince Edward Island' 'Newfoundland']
Filtered data saved to 'Ontario_Stations.csv'.
                       Name Province Climate ID  Station ID   WMO ID TC ID  \
5130           ATTAWAPISKAT  Ontario    6010387        3913      NaN   NaN
5131         ATTAWAPISKAT A  Ontario    6010400       52918  71653.0   YAT
5132       BIG TROUT LAKE A  Ontario    6010735       49488  71675.0   YTL
5133         BIG TROUT LAKE  Ontario    6010738        3914      NaN   NaN
5134  BIG TROUT LAKE READAC  Ontario    6010739       10804      NaN   TBL
...                     ...      ...        ...         ...      ...   ...
6767          BANCROFT AUTO  Ontario    616I001       26799  71294.0   WRK
6768           PETERBOROUGH  Ontario    616I002       26862      NaN   NaN
6769      BURNT RIVER-CLARK  Ontario    616J0FN        6958      NaN   NaN
6770               ROSEDALE  Ontario    616PA87        5151      NaN   NaN
6771                 WARSAW  Ontario    616RKR0        6912      NaN   NaN

      Latitude (Decimal Degrees)  Longitude (Decimal Degrees)   Latitude  \
5130                       52.92                       -82.45  525500000
5131                       52.93                       -82.43  525539000
5132                       53.82                       -89.90  534904000
5133                       53.83                       -89.87  535000000
5134                       53.82                       -89.90  534856000
...                          ...                          ...        ...
6767                       45.07                       -77.88  450417000
6768                       44.23                       -78.37  441400000
6769                       44.63                       -78.70  443800000
6770                       44.57                       -78.78  443400000
6771                       44.46                       -78.13  442746068

      Longitude  Elevation (m)  First Year  Last Year  HLY First Year  \
5130 -822700000            9.1        1968       1968             NaN
5131 -822555000            9.1        2015       2024          2015.0
5132 -895349000          222.5        2011       2024          2011.0
5133 -895200000          224.1        1939       1992          1953.0
5134 -895344000          222.2        1992       2013          1994.0
...         ...            ...         ...        ...             ...
6767 -775244000          330.7        1995       2024          1995.0
6768 -782200000          191.0        1995       1996          1995.0
6769 -784200000          259.0        1992       1992             NaN
6770 -784700000          259.1        1975       1994             NaN
6771 -780748036          230.0        1991       2008             NaN

      HLY Last Year  DLY First Year  DLY Last Year  MLY First Year  \
5130            NaN          1968.0         1968.0          1968.0
5131         2024.0          2015.0         2024.0             NaN
5132         2024.0          2011.0         2024.0             NaN
5133         1992.0          1939.0         1992.0          1939.0
5134         2013.0          1992.0         2013.0             NaN
...             ...             ...            ...             ...
6767         2024.0          1995.0         2024.0          1997.0
6768         1996.0             NaN            NaN             NaN
6769            NaN          1992.0         1992.0          1992.0
6770            NaN          1975.0         1994.0          1975.0
6771            NaN          1991.0         2008.0          1991.0

      MLY Last Year
5130         1968.0
5131            NaN
5132            NaN
5133         1992.0
5134            NaN
...             ...
6767         2006.0
6768            NaN
6769         1992.0
6770         1994.0
6771         2006.0

[1642 rows x 19 columns]

In [19]:
import pandas as pd

# Load the Ontario_Stations.csv file
file_name = "Ontario_Stations.csv"
data = pd.read_csv(file_name)

# Filter rows where 'Last Year' is 2004 or greater
filtered_data = data[data['Last Year'] >= 2024]

# Save the filtered data to a new CSV file
filtered_data.to_csv("Ontario_Stations_LastYear_2024.csv", index=False)

# Display the filtered data
print(filtered_data)

                          Name Province Climate ID  Station ID   WMO ID TC ID  \
1               ATTAWAPISKAT A  Ontario    6010400       52918  71653.0   YAT
2             BIG TROUT LAKE A  Ontario    6010735       49488  71675.0   YTL
5               BIG TROUT LAKE  Ontario    6010740       50857  71208.0   OTL
9              EAR FALLS (AUT)  Ontario    6012199       27865  71295.0   XEA
13               FORT SEVERN A  Ontario    6012501       51219  71099.0   YER
...                        ...      ...        ...         ...      ...   ...
1616            PETERBOROUGH A  Ontario    6166415       48952  71436.0   YPQ
1627  PETERBOROUGH TRENTU FARM  Ontario    6166457       55365  73180.0   OTU
1630    SONYA SUNDANCE MEADOWS  Ontario    6168100       31010      NaN   NaN
1631                    TAPLEY  Ontario    6168525       44205      NaN   NaN
1637             BANCROFT AUTO  Ontario    616I001       26799  71294.0   WRK

      Latitude (Decimal Degrees)  Longitude (Decimal Degrees)   Latitude  \
1                          52.93                       -82.43  525539000
2                          53.82                       -89.90  534904000
5                          53.82                       -89.89  534858000
9                          50.63                       -93.22  503750000
13                         56.02                       -87.68  560108000
...                          ...                          ...        ...
1616                       44.23                       -78.36  441348000
1627                       44.35                       -78.28  442114000
1630                       44.22                       -78.95  441300000
1631                       44.17                       -78.50  441014040
1637                       45.07                       -77.88  450417000

      Longitude  Elevation (m)  First Year  Last Year  HLY First Year  \
1    -822555000            9.1        2015       2024          2015.0
2    -895349000          222.5        2011       2024          2011.0
5    -895330000          222.5        2012       2024          2012.0
9    -931317000          362.6        1999       2024          2000.0
13   -874034000           15.8        2013       2024          2013.0
...         ...            ...         ...        ...             ...
1616 -782148000          191.4        2010       2024          2010.0
1627 -781642000          225.0        2022       2024          2022.0
1630 -785700000          275.0        2001       2024             NaN
1631 -783005094          270.0        2005       2024             NaN
1637 -775244000          330.7        1995       2024          1995.0

      HLY Last Year  DLY First Year  DLY Last Year  MLY First Year  \
1            2024.0          2015.0         2024.0             NaN
2            2024.0          2011.0         2024.0             NaN
5            2024.0          2012.0         2024.0             NaN
9            2024.0          1999.0         2024.0          1999.0
13           2024.0          2013.0         2024.0             NaN
...             ...             ...            ...             ...
1616         2024.0          2010.0         2024.0             NaN
1627         2024.0          2022.0         2024.0             NaN
1630            NaN          2001.0         2024.0          2001.0
1631            NaN          2005.0         2024.0          2005.0
1637         2024.0          1995.0         2024.0          1997.0

      MLY Last Year
1               NaN
2               NaN
5               NaN
9            2006.0
13              NaN
...             ...
1616            NaN
1627            NaN
1630         2006.0
1631         2006.0
1637         2006.0

[176 rows x 19 columns]

In [20]:
import pandas as pd

# Load the Ontario_Stations.csv file
file_name = "Ontario_Stations_LastYear_2024.csv"
data = pd.read_csv(file_name)

# Filter rows where 'Last Year' is 2004 or greater
filtered_data = data[data['First Year'] <= 2004]

# Save the filtered data to a new CSV file
filtered_data.to_csv("Ontario_Stations_FirstYear_2004_or_less.csv", index=False)

# Display the filtered data
print(filtered_data)

                       Name Province Climate ID  Station ID   WMO ID TC ID  \
3           EAR FALLS (AUT)  Ontario    6012199       27865  71295.0   XEA
6     LANSDOWNE HOUSE (AUT)  Ontario    6014353       10244  71846.0   WLF
8           PEAWANUCK (AUT)  Ontario    6016295       10197  71434.0   WWN
10        PICKLE LAKE (AUT)  Ontario    6016525        3920  71835.0   WPL
16                  BARWICK  Ontario    6020559        3932      NaN   NaN
..                      ...      ...        ...         ...      ...   ...
164            TORONTO CITY  Ontario    6158355       31688  71508.0   XTO
167               TRENTON A  Ontario    6158875        5126  71621.0   YTR
169      TORONTO NORTH YORK  Ontario    615S001       26953      NaN   NaN
173  SONYA SUNDANCE MEADOWS  Ontario    6168100       31010      NaN   NaN
175           BANCROFT AUTO  Ontario    616I001       26799  71294.0   WRK

     Latitude (Decimal Degrees)  Longitude (Decimal Degrees)   Latitude  \
3                         50.63                       -93.22  503750000
6                         52.20                       -87.94  521146000
8                         54.98                       -85.43  545900000
10                        51.45                       -90.22  512657001
16                        48.63                       -93.97  483800000
..                          ...                          ...        ...
164                       43.67                       -79.40  434000000
167                       44.12                       -77.53  440708000
169                       43.78                       -79.47  434648072
173                       44.22                       -78.95  441300000
175                       45.07                       -77.88  450417000

     Longitude  Elevation (m)  First Year  Last Year  HLY First Year  \
3   -931317000          362.6        1999       2024          2000.0
6   -875610000          253.4        1992       2024          1994.0
8   -852600000           52.7        1994       2024          1994.0
10  -901304007          390.8        1930       2024          1955.0
16  -935800000          335.0        1978       2024             NaN
..         ...            ...         ...        ...             ...
164 -792400000          112.5        2002       2024          2002.0
167 -773141000           86.3        1935       2024          1953.0
169 -792804038          187.0        1994       2024             NaN
173 -785700000          275.0        2001       2024             NaN
175 -775244000          330.7        1995       2024          1995.0

     HLY Last Year  DLY First Year  DLY Last Year  MLY First Year  \
3           2024.0          1999.0         2024.0          1999.0
6           2024.0          1992.0         2024.0          2000.0
8           2024.0          1994.0         2024.0          2003.0
10          2024.0          1930.0         2024.0          1930.0
16             NaN          1978.0         2024.0          1978.0
..             ...             ...            ...             ...
164         2024.0          2002.0         2024.0          2003.0
167         2024.0          1935.0         2024.0          1935.0
169            NaN          1994.0         2024.0          1994.0
173            NaN          2001.0         2024.0          2001.0
175         2024.0          1995.0         2024.0          1997.0

     MLY Last Year
3           2006.0
6           2006.0
8           2006.0
10          2006.0
16          2006.0
..             ...
164         2006.0
167         2017.0
169         2006.0
173         2006.0
175         2006.0

[83 rows x 19 columns]

In [22]:
import subprocess

# Define the URL for yearly data (timeframe set to 4 for yearly)
def download_yearly_data(station_id, year):
    url = f"https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID={station_id}&Year={year}&Month=1&Day=1&timeframe=4&submit= Download+Data"
    output_file = f"climate_data_{station_id}_{year}_yearly.csv"
    
    # Use subprocess to execute the wget command
    subprocess.run(["wget", "--content-disposition", "-O", output_file, url])

# List of station IDs for Ontario (assuming you have the list of all 1643 station IDs)
station_ids = [27865, 10244, 10197, 3920, 3932, 10220, 3966, 30455, 10899, 3987, 27674, 7582, 30682, 4057, 4061, 26912, 4121, 4140, 30435, 7633, 42967, 6901, 4243, 4255, 4268, 10903, 4287, 27534, 41738, 26773, 4333, 30578, 4352, 4377, 6900, 43540, 4432, 10911, 43046, 6904, 32128, 4509, 42183, 4525, 7733, 27604, 7747, 4607, 27528, 30266, 4647, 9026, 4656, 4671, 7790, 32473, 4689, 4699, 31367, 4715, 9005, 27533, 41983, 4760, 4761, 10999, 7844, 4816, 27647, 4835, 4859, 7868, 4898, 7870, 4905, 4923, 27529, 7925, 31688, 5126, 26953, 31010, 26799
]  # replace with actual station IDs

# Specific years to download data for
years_to_download = [2004, 2016, 2024]

# Download yearly data for each specific year (2004, 2016, and 2024) for each station
for station_id in station_ids:
    for year in years_to_download:
        download_yearly_data(station_id, year)

In [33]:
import os
os.chdir("E:/GIS/projects/climate_data")

In [35]:
import pandas as pd
import os

# List of station IDs
station_ids = [
    27865, 10244, 10197, 3920, 3932, 10220, 3966, 30455, 10899, 3987, 27674, 7582,
    30682, 4057, 4061, 26912, 4121, 4140, 30435, 7633, 42967, 6901, 4243, 4255, 4268,
    10903, 4287, 27534, 41738, 26773, 4333, 30578, 4352, 4377, 6900, 43540, 4432,
    10911, 43046, 6904, 32128, 4509, 42183, 4525, 7733, 27604, 7747, 4607, 27528,
    30266, 4647, 9026, 4656, 4671, 7790, 32473, 4689, 4699, 31367, 4715, 9005, 27533,
    41983, 4760, 4761, 10999, 7844, 4816, 27647, 4835, 4859, 7868, 4898, 7870, 4905,
    4923, 27529, 7925, 31688, 5126, 26953, 31010, 26799
]

# Years of interest
years = [2004, 2016, 2024]

# Output dictionary to store averages
averages = {}

# Loop through station IDs and years
for station_id in station_ids:
    for year in years:
        file_name = f"climate_data_{station_id}_{year}_yearly.csv"
        
        # Check if the file exists in the current directory
        if os.path.exists(file_name):
            # Load the CSV file into a DataFrame
            df = pd.read_csv(file_name)
            
            # Compute column averages and store in the dictionary
            # Skip non-numeric columns
            numeric_cols = df.select_dtypes(include='number')
            avg_values = numeric_cols.mean()
            
            # Store results in dictionary
            averages[f"{station_id}_{year}"] = avg_values.to_dict()
        else:
            print(f"File not found: {file_name}")

# Convert the dictionary to a DataFrame for easier viewing
averages_df = pd.DataFrame.from_dict(averages, orient='index')

# Save the averages to a new CSV file
averages_df.to_csv("averages_climate_data.csv")

# Print the DataFrame
print(averages_df)

            Longitude (x)  Latitude (y)  Climate ID     Month        Day  \
27865_2004         -93.22         50.63   6012199.0  6.513661  15.756831
27865_2016         -93.22         50.63   6012199.0  6.513661  15.756831
27865_2024         -93.22         50.63   6012199.0  6.513661  15.756831
10244_2004         -87.94         52.20   6014353.0  6.513661  15.756831
10244_2016         -87.94         52.20   6014353.0  6.513661  15.756831
...                   ...           ...         ...       ...        ...
31010_2016         -78.95         44.22   6168100.0  6.513661  15.756831
31010_2024         -78.95         44.22   6168100.0  6.513661  15.756831
26799_2004         -77.88         45.07         NaN  6.513661  15.756831
26799_2016         -77.88         45.07         NaN  6.513661  15.756831
26799_2024         -77.88         45.07         NaN  6.513661  15.756831

            Average Max. Temp. (°C)  Average Min. Temp. (°C)  \
27865_2004                      NaN                      NaN
27865_2016                      NaN                      NaN
27865_2024                      NaN                      NaN
10244_2004                      NaN                      NaN
10244_2016                      NaN                      NaN
...                             ...                      ...
31010_2016                      NaN                      NaN
31010_2024                      NaN                      NaN
26799_2004                      NaN                      NaN
26799_2016                      NaN                      NaN
26799_2024                      NaN                      NaN

            Frequency of Precip. (%)  Highest Temp. (°C)  Highest Temp.Year  \
27865_2004                       NaN           18.167213        2011.636612
27865_2016                       NaN           18.167213        2011.636612
27865_2024                       NaN           18.167213        2011.636612
10244_2004                       NaN           17.486339        2009.743169
10244_2016                       NaN           17.486339        2009.743169
...                              ...                 ...                ...
31010_2016                       NaN                 NaN                NaN
31010_2024                       NaN                 NaN                NaN
26799_2004                       NaN           21.780874        2010.896175
26799_2016                       NaN           21.780874        2010.896175
26799_2024                       NaN           21.780874        2010.896175

            ...  Greatest Precip. Data Quality  Greatest Rainfall (mm)  \
27865_2004  ...                            NaN                0.000000
27865_2016  ...                            NaN                0.000000
27865_2024  ...                            NaN                0.000000
10244_2004  ...                            NaN                0.087413
10244_2016  ...                            NaN                0.087413
...         ...                            ...                     ...
31010_2016  ...                            NaN               15.821585
31010_2024  ...                            NaN               15.821585
26799_2004  ...                            NaN                0.000000
26799_2016  ...                            NaN                0.000000
26799_2024  ...                            NaN                0.000000

            Greatest Rainfall Year  Greatest Rainfall Data Quality  \
27865_2004             2001.677656                             NaN
27865_2016             2001.677656                             NaN
27865_2024             2001.677656                             NaN
10244_2004             2005.993007                             NaN
10244_2016             2005.993007                             NaN
...                            ...                             ...
31010_2016             2011.500000                             NaN
31010_2024             2011.500000                             NaN
26799_2004             1999.171598                             NaN
26799_2016             1999.171598                             NaN
26799_2024             1999.171598                             NaN

            Greatest Snowfall (cm)  Greatest Snowfall Year  \
27865_2004                2.767241             2004.158621
27865_2016                2.767241             2004.158621
27865_2024                2.767241             2004.158621
10244_2004                3.574242             2007.030303
10244_2016                3.574242             2007.030303
...                            ...                     ...
31010_2016                4.263934             2007.633880
31010_2024                4.263934             2007.633880
26799_2004                4.630939             2003.983425
26799_2016                4.630939             2003.983425
26799_2024                4.630939             2003.983425

            Greatest Snowfall Data Quality  Most Snow on the Ground (cm)  \
27865_2004                             NaN                     26.592896
27865_2016                             NaN                     26.592896
27865_2024                             NaN                     26.592896
10244_2004                             NaN                     23.756831
10244_2016                             NaN                     23.756831
...                                    ...                           ...
31010_2016                             NaN                     11.898907
31010_2024                             NaN                     11.898907
26799_2004                             NaN                     18.781421
26799_2016                             NaN                     18.781421
26799_2024                             NaN                     18.781421

            Most Snow on the Ground Year  Most Snow on the Ground Data Quality
27865_2004                   2008.306011                                   NaN
27865_2016                   2008.306011                                   NaN
27865_2024                   2008.306011                                   NaN
10244_2004                   2007.874317                                   NaN
10244_2016                   2007.874317                                   NaN
...                                  ...                                   ...
31010_2016                   2005.248634                                   NaN
31010_2024                   2005.248634                                   NaN
26799_2004                   2004.633880                                   NaN
26799_2016                   2004.633880                                   NaN
26799_2024                   2004.633880                                   NaN

[249 rows x 26 columns]

In [36]:
import os
os.chdir("E:/GIS/projects/climate_data/filtered")

In [46]:
import pandas as pd

# Load the CSV file into a pandas DataFrame
file_name = "averages_climate_data.csv"  # Replace with your actual file name
data = pd.read_csv(file_name)

# Strip leading/trailing spaces from column names
data.columns = data.columns.str.strip()

# Extract the year from the 'year' column (assumes 'year' format is 'StationID_Year')
data['Year'] = data['year'].str.split('_').str[1].astype(int)  # Extract year and convert to int

# Filter the data to only include rows where the Year is 2004
data_2004 = data[data['Year'] == 2004]

# Display the filtered data for 2004
print(data_2004)

# Optionally, save the filtered data to a new CSV file
output_file_2004 = "climate_data_2004.csv"
data_2004.to_csv(output_file_2004, index=False)

           year  Longitude (x)  Latitude (y)  Climate ID     Month        Day  \
0    27865_2004         -93.22         50.63   6012199.0  6.513661  15.756831
3    10244_2004         -87.94         52.20   6014353.0  6.513661  15.756831
6    10197_2004         -85.43         54.98   6016295.0  6.513661  15.756831
9     3920_2004         -90.22         51.45   6016525.0  6.513661  15.756831
12    3932_2004         -93.97         48.63   6020559.0  6.513661  15.756831
..          ...            ...           ...         ...       ...        ...
234  31688_2004         -79.40         43.67   6158355.0  6.513661  15.756831
237   5126_2004         -77.53         44.12   6158875.0  6.513661  15.756831
240  26953_2004         -79.47         43.78         NaN  6.513661  15.756831
243  31010_2004         -78.95         44.22   6168100.0  6.513661  15.756831
246  26799_2004         -77.88         45.07         NaN  6.513661  15.756831

     Average Max. Temp. (°C)  Average Min. Temp. (°C)  \
0                        NaN                      NaN
3                        NaN                      NaN
6                        NaN                      NaN
9                   5.361475                -5.975410
12                  8.956831                -2.557923
..                       ...                      ...
234                      NaN                      NaN
237                12.113388                 1.839344
240                      NaN                      NaN
243                      NaN                      NaN
246                      NaN                      NaN

     Frequency of Precip. (%)  Highest Temp. (°C)  ...  \
0                         NaN           18.167213  ...
3                         NaN           17.486339  ...
6                         NaN           14.678142  ...
9                         NaN           18.695628  ...
12                  40.265027           21.778689  ...
..                        ...                 ...  ...
234                       NaN           22.498634  ...
237                 41.983607           23.137158  ...
240                       NaN           23.775137  ...
243                       NaN                 NaN  ...
246                       NaN           21.780874  ...

     Greatest Rainfall (mm)  Greatest Rainfall Year  \
0                  0.000000             2001.677656
3                  0.087413             2005.993007
6                  0.019643             1999.589286
9                 14.917760             1957.928962
12                20.380874             2000.631148
..                      ...                     ...
234                0.000000             2007.164384
237               33.062295             1983.857923
240               22.340984             2008.806011
243               15.821585             2011.500000
246                0.000000             1999.171598

     Greatest Rainfall Data Quality  Greatest Snowfall (cm)  \
0                               NaN                2.767241
3                               NaN                3.574242
6                               NaN                3.547879
9                               NaN                9.138798
12                              NaN                5.175683
..                              ...                     ...
234                             NaN                4.515000
237                             NaN                7.295628
240                             NaN                4.251366
243                             NaN                4.263934
246                             NaN                4.630939

     Greatest Snowfall Year  Greatest Snowfall Data Quality  \
0               2004.158621                             NaN
3               2007.030303                             NaN
6               2005.454545                             NaN
9               1955.841530                             NaN
12              1993.292350                             NaN
..                      ...                             ...
234             2006.970000                             NaN
237             1958.396175                             NaN
240             2001.374317                             NaN
243             2007.633880                             NaN
246             2003.983425                             NaN

     Most Snow on the Ground (cm)  Most Snow on the Ground Year  \
0                       26.592896                   2008.306011
3                       23.756831                   2007.874317
6                       27.549180                   2007.174863
9                       43.267760                   1966.060109
12                      21.284153                   1996.806011
..                            ...                           ...
234                      7.090164                   2006.478142
237                     13.341530                   1969.128415
240                     10.431694                   2001.065574
243                     11.898907                   2005.248634
246                     18.781421                   2004.633880

     Most Snow on the Ground Data Quality  Year
0                                     NaN  2004
3                                     NaN  2004
6                                     NaN  2004
9                                     NaN  2004
12                                    NaN  2004
..                                    ...   ...
234                                   NaN  2004
237                                   NaN  2004
240                                   NaN  2004
243                                   NaN  2004
246                                   NaN  2004

[83 rows x 28 columns]

In [49]:
import pandas as pd

# Load the 2004 climate data CSV file into a pandas DataFrame
file_name = "climate_data_2004.csv"  # Replace with your actual file name
data_2004 = pd.read_csv(file_name)

# Strip leading/trailing spaces from column names
data_2004.columns = data_2004.columns.str.strip()

# Calculate the average value of each numeric column
average_values = data_2004.mean()

# Save the average values to a new CSV file
average_values.to_csv("average_climate_data_2004.csv", header=True)

# Display the average values
print("Average values for each column have been saved to 'average_climate_data_2004.csv'.")

Average values for each column have been saved to 'average_climate_data_2004.csv'.

In [50]:
import pandas as pd

# Load the CSV file into a pandas DataFrame
file_name = "averages_climate_data.csv"  # Replace with your actual file name
data = pd.read_csv(file_name)

# Strip leading/trailing spaces from column names
data.columns = data.columns.str.strip()

# Extract the year from the 'year' column (assumes 'year' format is 'StationID_Year')
data['Year'] = data['year'].str.split('_').str[1].astype(int)  # Extract year and convert to int

# Filter the data to only include rows where the Year is 2016
data_2016 = data[data['Year'] == 2016]

# Display the filtered data for 2016
print(data_2016)

# Optionally, save the filtered data to a new CSV file
output_file_2016 = "climate_data_2016.csv"
data_2016.to_csv(output_file_2016, index=False)

           year  Longitude (x)  Latitude (y)  Climate ID     Month        Day  \
1    27865_2016         -93.22         50.63   6012199.0  6.513661  15.756831
4    10244_2016         -87.94         52.20   6014353.0  6.513661  15.756831
7    10197_2016         -85.43         54.98   6016295.0  6.513661  15.756831
10    3920_2016         -90.22         51.45   6016525.0  6.513661  15.756831
13    3932_2016         -93.97         48.63   6020559.0  6.513661  15.756831
..          ...            ...           ...         ...       ...        ...
235  31688_2016         -79.40         43.67   6158355.0  6.513661  15.756831
238   5126_2016         -77.53         44.12   6158875.0  6.513661  15.756831
241  26953_2016         -79.47         43.78         NaN  6.513661  15.756831
244  31010_2016         -78.95         44.22   6168100.0  6.513661  15.756831
247  26799_2016         -77.88         45.07         NaN  6.513661  15.756831

     Average Max. Temp. (°C)  Average Min. Temp. (°C)  \
1                        NaN                      NaN
4                        NaN                      NaN
7                        NaN                      NaN
10                  5.361475                -5.975410
13                  8.956831                -2.557923
..                       ...                      ...
235                      NaN                      NaN
238                12.113388                 1.839344
241                      NaN                      NaN
244                      NaN                      NaN
247                      NaN                      NaN

     Frequency of Precip. (%)  Highest Temp. (°C)  ...  \
1                         NaN           18.167213  ...
4                         NaN           17.486339  ...
7                         NaN           14.678142  ...
10                        NaN           18.695628  ...
13                  40.265027           21.778689  ...
..                        ...                 ...  ...
235                       NaN           22.498634  ...
238                 41.983607           23.137158  ...
241                       NaN           23.775137  ...
244                       NaN                 NaN  ...
247                       NaN           21.780874  ...

     Greatest Rainfall (mm)  Greatest Rainfall Year  \
1                  0.000000             2001.677656
4                  0.087413             2005.993007
7                  0.019643             1999.589286
10                14.917760             1957.928962
13                20.380874             2000.631148
..                      ...                     ...
235                0.000000             2007.164384
238               33.062295             1983.857923
241               22.340984             2008.806011
244               15.821585             2011.500000
247                0.000000             1999.171598

     Greatest Rainfall Data Quality  Greatest Snowfall (cm)  \
1                               NaN                2.767241
4                               NaN                3.574242
7                               NaN                3.547879
10                              NaN                9.138798
13                              NaN                5.175683
..                              ...                     ...
235                             NaN                4.515000
238                             NaN                7.295628
241                             NaN                4.251366
244                             NaN                4.263934
247                             NaN                4.630939

     Greatest Snowfall Year  Greatest Snowfall Data Quality  \
1               2004.158621                             NaN
4               2007.030303                             NaN
7               2005.454545                             NaN
10              1955.841530                             NaN
13              1993.292350                             NaN
..                      ...                             ...
235             2006.970000                             NaN
238             1958.396175                             NaN
241             2001.374317                             NaN
244             2007.633880                             NaN
247             2003.983425                             NaN

     Most Snow on the Ground (cm)  Most Snow on the Ground Year  \
1                       26.592896                   2008.306011
4                       23.756831                   2007.874317
7                       27.549180                   2007.174863
10                      43.267760                   1966.060109
13                      21.284153                   1996.806011
..                            ...                           ...
235                      7.090164                   2006.478142
238                     13.341530                   1969.128415
241                     10.431694                   2001.065574
244                     11.898907                   2005.248634
247                     18.781421                   2004.633880

     Most Snow on the Ground Data Quality  Year
1                                     NaN  2016
4                                     NaN  2016
7                                     NaN  2016
10                                    NaN  2016
13                                    NaN  2016
..                                    ...   ...
235                                   NaN  2016
238                                   NaN  2016
241                                   NaN  2016
244                                   NaN  2016
247                                   NaN  2016

[83 rows x 28 columns]

In [51]:
import pandas as pd

# Load the 2016 climate data CSV file into a pandas DataFrame
file_name = "climate_data_2016.csv"  # Replace with your actual file name
data_2016 = pd.read_csv(file_name)

# Strip leading/trailing spaces from column names
data_2016.columns = data_2016.columns.str.strip()

# Calculate the average value of each numeric column
average_values = data_2016.mean()

# Save the average values to a new CSV file
average_values.to_csv("average_climate_data_2016.csv", header=True)

# Display the average values
print("Average values for each column have been saved to 'average_climate_data_2016.csv'.")

Average values for each column have been saved to 'average_climate_data_2016.csv'.